name: Release Tesseract Training Data

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Prepare tessdata for release
        run: |
          # Copy configs directory into tessdata if it exists
          if [ -d "configs" ]; then
            cp -r configs tessdata/
          fi
          
          # List files for verification
          echo "Files in tessdata directory:"
          ls -la tessdata/
          
      - name: Create archive
        run: |
          # Create tar.gz archive
          tar -czf tesseract-traineddata.tar.gz tessdata/
          
          # Show archive info
          echo "Archive created:"
          ls -lh tesseract-traineddata.tar.gz
          
      - name: Determine tag name
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Tesseract Training Data ${{ steps.tag.outputs.tag_name }}
          body: |
            ## Tesseract Training Data Release
            
            This release contains Tesseract OCR training data files (tessdata) for multiple languages.
            
            ### Contents
            - Language training data files (*.traineddata)
            - Configuration files
            
            ### Usage
            1. Download the `tesseract-traineddata.tar.gz` file
            2. Extract it to your Tesseract tessdata directory
            3. Use with Tesseract OCR for multi-language text recognition
            
            **Archive:** `tesseract-traineddata.tar.gz`
          files: |
            tesseract-traineddata.tar.gz
            tessdata/afr.traineddata
            tessdata/amh.traineddata
            tessdata/ara.traineddata
            tessdata/asm.traineddata
            tessdata/aze.traineddata
            tessdata/aze_cyrl.traineddata
            tessdata/bel.traineddata
            tessdata/ben.traineddata
            tessdata/bod.traineddata
            tessdata/bos.traineddata
            tessdata/bre.traineddata
            tessdata/bul.traineddata
            tessdata/cat.traineddata
            tessdata/ceb.traineddata
            tessdata/ces.traineddata
            tessdata/chi_sim.traineddata
            tessdata/chi_sim_vert.traineddata
            tessdata/chi_tra.traineddata
            tessdata/chi_tra_vert.traineddata
            tessdata/chr.traineddata
            tessdata/cos.traineddata
            tessdata/cym.traineddata
            tessdata/dan.traineddata
            tessdata/dan_frak.traineddata
            tessdata/deu_frak.traineddata
            tessdata/deu_latf.traineddata
            tessdata/div.traineddata
            tessdata/dut.traineddata
            tessdata/dzo.traineddata
            tessdata/ell.traineddata
            tessdata/eng.traineddata
            tessdata/enm.traineddata
            tessdata/epo.traineddata
            tessdata/equ.traineddata
            tessdata/est.traineddata
            tessdata/eus.traineddata
            tessdata/fao.traineddata
            tessdata/fas.traineddata
            tessdata/fil.traineddata
            tessdata/fin.traineddata
            tessdata/fra.traineddata
            tessdata/frm.traineddata
            tessdata/fry.traineddata
            tessdata/ger.traineddata
            tessdata/gla.traineddata
            tessdata/gle.traineddata
            tessdata/glg.traineddata
            tessdata/grc.traineddata
            tessdata/guj.traineddata
            tessdata/hat.traineddata
            tessdata/heb.traineddata
            tessdata/hin.traineddata
            tessdata/hrv.traineddata
            tessdata/hun.traineddata
            tessdata/hye.traineddata
            tessdata/iku.traineddata
            tessdata/ind.traineddata
            tessdata/isl.traineddata
            tessdata/ita.traineddata
            tessdata/ita_old.traineddata
            tessdata/jav.traineddata
            tessdata/jpn.traineddata
            tessdata/jpn_vert.traineddata
            tessdata/kan.traineddata
            tessdata/kat.traineddata
            tessdata/kat_old.traineddata
            tessdata/kaz.traineddata
            tessdata/khm.traineddata
            tessdata/kir.traineddata
            tessdata/kmr.traineddata
            tessdata/kor.traineddata
            tessdata/kor_vert.traineddata
            tessdata/lao.traineddata
            tessdata/lat.traineddata
            tessdata/lav.traineddata
            tessdata/lit.traineddata
            tessdata/ltz.traineddata
            tessdata/mal.traineddata
            tessdata/mar.traineddata
            tessdata/mkd.traineddata
            tessdata/mlt.traineddata
            tessdata/mon.traineddata
            tessdata/mri.traineddata
            tessdata/msa.traineddata
            tessdata/mya.traineddata
            tessdata/nep.traineddata
            tessdata/nor.traineddata
            tessdata/oci.traineddata
            tessdata/ori.traineddata
            tessdata/osd.traineddata
            tessdata/pan.traineddata
            tessdata/pol.traineddata
            tessdata/por.traineddata
            tessdata/pus.traineddata
            tessdata/que.traineddata
            tessdata/ron.traineddata
            tessdata/rus.traineddata
            tessdata/san.traineddata
            tessdata/sin.traineddata
            tessdata/slk.traineddata
            tessdata/slk_frak.traineddata
            tessdata/slv.traineddata
            tessdata/snd.traineddata
            tessdata/spa.traineddata
            tessdata/spa_old.traineddata
            tessdata/sqi.traineddata
            tessdata/srp.traineddata
            tessdata/srp_latn.traineddata
            tessdata/sun.traineddata
            tessdata/swa.traineddata
            tessdata/swe.traineddata
            tessdata/syr.traineddata
            tessdata/tam.traineddata
            tessdata/tat.traineddata
            tessdata/tel.traineddata
            tessdata/tgk.traineddata
            tessdata/tgl.traineddata
            tessdata/tha.traineddata
            tessdata/tir.traineddata
            tessdata/ton.traineddata
            tessdata/tur.traineddata
            tessdata/uig.traineddata
            tessdata/ukr.traineddata
            tessdata/urd.traineddata
            tessdata/uzb.traineddata
            tessdata/uzb_cyrl.traineddata
            tessdata/vie.traineddata
            tessdata/yid.traineddata
            tessdata/yor.traineddata
          draft: false
          prerelease: false